# name of my workflow
name: TestPipeline

# events 
on:
  # workflow_run:
  #   workflows: ['TrainPipeline']
  #     types:
  #       - completed
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  




# groups set of actions that needs to execute
jobs:
  evaluation:
    env:
      # (or) make sure readS3FullAccess ROLE attached to Runner
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
    # EC2 Instance
    runs-on: self-hosted

    steps:
      # copy code to machine
      - uses: actions/checkout@v4


      # install deps
      - name: Set requirements
        run: pip install -r requirements.txt

      # removing dataset & old confusion-matrcies ğŸŒ€ğŸ˜¶â€ğŸŒ«ï¸
      - name: cleaning existing files ğŸª¥
        run: make trash
      
      # download dataset
      - name: download dataset from s3
        run: make pull

      - name: make sure tensorboard not starts
        run: make showoff

      # hparams already mentioned in configs/eval.yaml
      # confusion matrix saved and printed!!
      - name: running evaluation on already trained-model::Nov-09-2024-3:51AM
        run: |
          make eval